const produtos = [
	{
		nome: "Banana",
		preco: 4,
		secao: "Hortifruti",
		categoria: "fruta",
		img: "./src/img/banana.png",
	},
	{
		nome: "Morango 5kg",
		preco: 7,
		secao: "Hortifruti",
		categoria: "fruta",
		img: "./src/img/morango.png",
	},
	{
		nome: "Maçã",
		preco: 4,
		secao: "Hortifruti",
		categoria: "fruta",
		img: "./src/img/maca.png",
	},
	{
		nome: "Pão",
		preco: 5,
		secao: "Panificadora",
		categoria: "Pães",
		img: "./src/img/pao.png",
	},
	{
		nome: "Leite",
		preco: 7,
		secao: "Laticínio",
		categoria: "Leite",
		img: "./src/img/leite.png",
	},
	{
		nome: "Bolo",
		preco: 10,
		secao: "Panificadora",
		categoria: "Leite",
		img: "./src/img/bolo.png",
	},
	{
		nome: "Yorgut de Morango",
		preco: 3,
		secao: "Laticínio",
		categoria: "Leite",
		img: "./src/img/yorgut.png",
	},
	{
		nome: "Torta de Maçã",
		preco: 4,
		secao: "Hortifruti",
		categoria: "fruta",
		img: "./src/img/tortamaca.png",
	},
];
